### ISSUE TITLE
Argument t_eval raises error

### ISSUE THREAD

**Issue by RoKo-reuther** [maurosilber/scipy-events#1]
Hello,

I encoutered a problem when trying to specify the argument t_eval: ValueError: Values in `t_eval`are not within `t_span`,
when the specified values in t_eval were well within t_span.
The version is 0.4.1.

**Comment by maurosilber** [comment]
Hi!

Can you provide a minimal example to reproduce the issue?

**Comment by RoKo-reuther** [comment]
Thank you for your quick reply!

Here's the basic example with argument t_eval:

```py
import numpy as np
from scipy_events import ChangeAt, solve_ivp

result = solve_ivp(
    lambda t, y: -y,
    t_eval=[1],
    t_span=(0, 16),
    y0=[1],
    events=[
        ChangeAt(
            times=[4, 8],
            change=lambda t, y, args: (np.full_like(y, 1), args),
        )
    ],
)
```

**Comment by maurosilber** [comment]
Thanks! I just released a new version (0.4.2) with a fix. If you used conda-forge to install this package, it will take some time (hours?) appear there, but it is already available on PyPI.

**Comment by RoKo-reuther** [comment]
Super, thank you very much!

**Comment by RoKo-reuther** [comment]
Hello,
thank you again for your quick fix.
There is still an issue remaining when t_eval is after the first event.

```py
import numpy as np
from scipy_events import ChangeAt, solve_ivp

result = solve_ivp(
    lambda t, y: -y,
    t_eval=[5],
    t_span=(0, 16),
    y0=[1],
    events=[
        ChangeAt(
            times=[4, 8],
            change=lambda t, y, args: (np.full_like(y, 1), args),
        )
    ],
)
```

will still raise ValueError: Values in `t_eval` are not within `t_span`.

**Comment by maurosilber** [comment]
Yes, today I realized that I only fixed the case when all `t_eval` is less that than first change. I have already released a new version, 0.4.4. Does it work if you update?

**Comment by RoKo-reuther** [comment]
The update works, thank you!
